### ISSUE TITLE
leaflet.wms and leaflet.draw not working well together?

### ISSUE THREAD

**Issue by JJeurissen** [heigeo/leaflet.wms#14]
It seems that the delete button doesn't work in leaflet.draw after scrolling and while L.WMS.source is active.  I put together a quick jsfiddle.  http://jsfiddle.net/ysggo1b5/

Steps to replicate:
1) Draw a polygon.
2) Press the delete button.  You should be able to delete the polygon if you haven't scrolled and/or zoomed yet.
3) Scroll/zoom on the map.  You will no longer be able to delete the polygon.
4) If you comment out the line "overlays['Counties']={layer:source.getLayer('county_borders').addTo(map)};" (or just .addTo(map)), reload, and repeat the steps the polygon is now always removable.

**Comment by sheppard** [comment]
Yes this seems like a bug related to the [internal overlay swapping](https://github.com/heigeo/leaflet.wms/blob/gh-pages/leaflet.wms.js#L335-L349) we're using to keep the image from flickering during zoom & pan.

The best solution will probably be to call `overlay.bringToBack()` on the internal overlay after adding it.  We could also define `bringToBack()` and `bringToFront()` on `wms.Overlay` and have it keep track of which one was called last.  (c.f. [esri-leaflet's code](https://github.com/Esri/esri-leaflet/blob/master/src/Layers/RasterLayer.js#L158-L162) that handles a similar use case)

**Comment by sheppard** [comment]
I believe this is fixed with #28.
