### ISSUE TITLE
tiled is a geoserver param

### ISSUE THREAD

**Issue by jfgodoy** [heigeo/leaflet.wms#16]
To enable geoserver wms service with geowebcache is needed to pass `tiled=true` as param, but this is filtered by leaflet.wms :(
http://docs.geoserver.org/stable/en/user/webadmin/tilecache/defaults.html#enable-direct-integration-with-geoserver-wms

**Comment by sheppard** [comment]
Hmm, yes that's a problem.  We'll probably need to change the option name - perhaps to `untiled` with the default of `true`?  A temporary workaround would be to add `&tiled=true` to your base WMS url, i.e.:

``` javascript
var s = L.WMS.source("http://example.com/mapserv?tiled=true", {
    'transparent': true,
    'tiled': true
});
```

The ideal solution would be to treat WMS parameters entirely separately from the layer options, but we're punting on that for now for compatibility with Leaflet (see Leaflet/Leaflet#2972).
