### ISSUE TITLE
"X and Y incorrectly specified"

### ISSUE THREAD

**Issue by hoge6b01** [heigeo/leaflet.wms#17]
Hi,

thanks for you great peace of code. I love the embedded popup function.
But it's not working as expected. 
Clicking on a WMS feature gives me 
**"X and Y incorrectly specified".**
The WMS is coming from my hosted geoserver with ESPG: 3857
Do you have a clue what I have to change?
Thanks

edit: If you need the code I can publish it on a JSFiddle

**Comment by sheppard** [comment]
This should be fixed in #24, let us know otherwise.

**Comment by lefcgis** [comment]
Hi guys. I have the same problem (X and Y incorrectly specified). However, I've tried to understand the answer but it's not clear for me. Please, Can you explain more details to resolve it?. I know is a CLOSED issue. Please, help me.

Lucho

**Comment by apdevelop** [comment]
> I have the same problem (X and Y incorrectly specified).

Could you provide some details? Browser request / response and what WMS server you use at least.

**Comment by lefcgis** [comment]
Hi @apdevelop , yes. I'm working in localhost. I have a web map developed with Leaflet, databases in PostGIS and web map server in GeoServer. I instantiate many layers.
![1](https://user-images.githubusercontent.com/13573242/116577501-24468080-a8d6-11eb-80b9-e324a1532c46.png)
In first picture, you can identify a specific layer (Primaria), and popUp works good.

![2](https://user-images.githubusercontent.com/13573242/116577665-4c35e400-a8d6-11eb-880a-07fc496df29f.png)
Second picture, turn on 'Secundaria' layer, but you can't review the popup information.

![3](https://user-images.githubusercontent.com/13573242/116577812-7091c080-a8d6-11eb-8534-8908ca644108.png)
When I inspectioned, I have 2 error messages.

![4](https://user-images.githubusercontent.com/13573242/116577911-856e5400-a8d6-11eb-91e7-0b32c743dc5f.png)
Panel said me: <serviceexception code = "InvalidPoint"> X and Y incorrectly specified.

Thanks!!!

**Comment by apdevelop** [comment]
@lefcgis, the most important information is on `Network` tab, where you can see all details of client (leaflet.wms library) `GetFeatureInfo` request and server (WMS) response. 
Without it I can only intuitively suggest, that there is possible issue with declared/used WMS protocol version: the `1.1.1` version use parameters named `x` and `y`, the `1.3.0` use `i` and `j` with the same meaning. In both cases they must be integer numbers (pixel coordinates).

**Comment by lefcgis** [comment]
Hi @apdevelop . I'm sorry for delayed. I attach the specific image that you mentioned. I can't resolve yet
![1](https://user-images.githubusercontent.com/13573242/118574162-7e09d000-b749-11eb-9442-35ab15c8678d.png)

**Comment by apdevelop** [comment]
> I attach the specific image

Unfortunately, the details (url parameters) of these `GetFeatureInfo` requests  (the 2nd and 3rd requests from the top) aren't visible. You can view details (Query String Parameters) after click on it, or just copy the entire request url and paste it here.

**Comment by lefcgis** [comment]
Thank you for your answer @apdevelop . Sorry for my bad English. I'm trying to understand it. I hope these steps are correctly and asnwer your requests.

![1](https://user-images.githubusercontent.com/13573242/118824915-dc38cf00-b87f-11eb-8567-fbcba5195c7d.png)
![2](https://user-images.githubusercontent.com/13573242/118824924-de029280-b87f-11eb-8845-f8a4a48d2b91.png)

Please, tell me if it is correct.

L.

**Comment by apdevelop** [comment]
> Please, tell me if it is correct.

You provided some weather service requests, but we need to see the `WMS` `GetFeatureInfo` network requests

**Comment by inzamambaig** [comment]
![1](https://user-images.githubusercontent.com/13573242/116577501-24468080-a8d6-11eb-80b9-e324a1532c46.png) 

@lefcgis Hi, I am using betterwms and getting the same `X and Y incorrectly specified`. Sometimes it shows the feature's attributes but other times it displays this error. In addition, How did you generate that wms getFeatureInfo pop-up? Your styling looks good, the betterwms displays in tabular form and I want to show it like yours instead of a table.
