### ISSUE TITLE
Tiles become blank after loading with latest leaflet in example

### ISSUE THREAD

**Issue by rdewit** [heigeo/leaflet.wms#18]
When using the leaflet.wms example with the latest version of leaflet (either git master or the 0.8-dev zip file), in the tiled mode the tiles load visibly and then become blank within about one second (their opacity gets set to 0).

When zooming the map in and out or moving the map around, the tiles become visible again.

It does not happen with the version of leaflet that comes with leaflet.wms.

**Comment by slongberry** [comment]
I am seeing this same problem. Image mode works fine, but tiled mode does not display the tiles even though I can see the images being returned from the server.

**Comment by sheppard** [comment]
This appears to be working with Leaflet 1.0.0-rc.2, let us know otherwise.
