### ISSUE TITLE
Object.keys not available in IE8

### ISSUE THREAD

**Issue by rdewit** [heigeo/leaflet.wms#20]
In refreshOverlay Object.keys is used which is available in IE9 onwards but not in IE8.

IIRC, Leaflet still plans to support IE8 in version 1.x. Are you planning on staying in line with Leaflet by supporting IE8 for leaflet.wms?

**Comment by r1m** [comment]
You can use : [es5-shim](https://github.com/es-shims/es5-shim)

**Comment by sheppard** [comment]
Yes, I usually use es5-shim but it was easy enough to implement a quick one here.
