### ISSUE TITLE
Overwrite

### ISSUE THREAD

**Issue by t-book** [heigeo/leaflet.wms#43]
Hi, 
can one show me how to correctly limit the amount of layers that are identified.
I´ve tried an extend like this which unfortunately is not working.

```
var MySource = L.WMS.Source.extend({
 'getIdentifyLayers': function() {
      var a = ['geonode:tl_2016_us_tbg']
      console.log(a);
      return a;
    }
    }
});


var source = new MySource("http://node.local/geoserver/wms", {
    'transparent': true
});
```

**Comment by sheppard** [comment]
Yes, extend is the recommended approach.  Can you provide more detail as to what isn't working?
