### ISSUE TITLE
transparent not working?

### ISSUE THREAD

**Issue by tomchadwin** [heigeo/leaflet.wms#51]
I'm trying to switch from `L.TileLayer.wms` to `L.WMS`. However, nodata pixels which were rendered transparent in `L.TileLayer.wms` are black with `L.WMS`. Here is my old and new code:

```javascript
var overlay_GBRBGS1625kBedrockLithology_0 = L.tileLayer.wms('http://ogc.bgs.ac.uk/cgi-bin/BGS_Bedrock_and_Superficial_Geology/wms?', {
    layers: 'GBR_BGS_625k_BLT',
    format: 'image/png',
    uppercase: true,
    transparent: true,
    continuousWorld : true,
    opacity: 1.0
});
```

```javascript
var overlay_GBRBGS1625kBedrockLithology_0 = L.WMS.source("http://ogc.bgs.ac.uk/cgi-bin/BGS_Bedrock_and_Superficial_Geology/wms?", {
    'transparent': true,
    tiled: true
});
overlay_GBRBGS1625kBedrockLithology_0.getLayer("GBR_BGS_625k_BLT").addTo(map);
```

Am I missing something?

**Comment by tomchadwin** [comment]
Ah, it's because when using `L.TileLayer.wms` I was passing in `format` to get PNGs back, but `L.WMS` defaults to JPEG, so no transparency. Is there a way to specify WMS options/params when using `L.WMS`? I've submitted #52, but I don't know if it's needed, or whether I'm just not understanding how to achieve what I need.

**Comment by sebastianvitterso** [comment]
Did you solve this? Feel free to post how you solved your issue, or the reason you didn't need help anymore.

**Comment by ydrea** [comment]
I solved it by modifying the default values:
```
309.        'format': 'image/png',
310.        'transparent': true
```
