### ISSUE TITLE
tiled layer do not display

### ISSUE THREAD

**Issue by dfy167** [heigeo/leaflet.wms#56]
```
var options = {
        transparent: true,
        format: 'image/png'
      }
 var source = window.L.WMS.source(
        'http://e/geoserver/FAST/wms',
        options
      )
      source.addSubLayer('layer')
```
works fine. but 
var options = {
        transparent: true,
        format: 'image/png',
        _tiled:true_      }
the tile is 0*256 and not show
leaflet 1.3 ,chrome latest

**Comment by apdevelop** [comment]
Did you compare URLs of requests to WMS in these two cases ?
Just checked, works normal with my own WMS service, sending several requests with `&tiled=true&width=256&height=256` instead of single one.

**Comment by dfy167** [comment]
with some test. it is ok.
i used a css framwork to set img's max-width:100%

fix by add 
```
.leaflet-container img {
  max-width: none;
}
```
