### ISSUE TITLE
Opacity in L.WMS.overlay Ignored

### ISSUE THREAD

**Issue by JJeurissen** [heigeo/leaflet.wms#9]
In the update function it looks like the opacity is set to 1 instead of using what was defined in the options.

**Comment by sheppard** [comment]
Thanks, could you put together a fix for this?

**Comment by JJeurissen** [comment]
Fixed in 017075c5491fac68c16b714ff560c7649cbebac7

**Comment by sheppard** [comment]
This works, though could you use `options.opacity` instead of `wmsParams.opacity` since opacity isn't really a WMS parameter?  You'll need to update the [`optNames` list](https://github.com/heigeo/leaflet.wms/blob/gh-pages/leaflet.wms.js#L258-L264) to mark opacity as an option.

**Comment by sheppard** [comment]
Related: Leaflet/Leaflet#2972

**Comment by JJeurissen** [comment]
I thought it was strange why there wasn't anything in the options.

**Comment by sheppard** [comment]
This is good for now, though we should revisit how the options are handled to match however Leaflet/Leaflet#2972 is resolved.
